//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW_18_2_PSD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_Transaction
    {
        public int HeaderTransactionID { get; set; }
        public int ShoeID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Header_Transaction Header_Transaction { get; set; }
        public virtual Sho Sho { get; set; }
    }
}
