//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW_18_2_PSD.HTService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HTService.HTControllerSoap")]
    public interface HTControllerSoap {
        
        // CODEGEN: Generating message contract since element name getAllHTResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllHT", ReplyAction="*")]
        LW_18_2_PSD.HTService.getAllHTResponse getAllHT(LW_18_2_PSD.HTService.getAllHTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllHT", ReplyAction="*")]
        System.Threading.Tasks.Task<LW_18_2_PSD.HTService.getAllHTResponse> getAllHTAsync(LW_18_2_PSD.HTService.getAllHTRequest request);
        
        // CODEGEN: Generating message contract since element name getHTByIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHTByID", ReplyAction="*")]
        LW_18_2_PSD.HTService.getHTByIDResponse getHTByID(LW_18_2_PSD.HTService.getHTByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHTByID", ReplyAction="*")]
        System.Threading.Tasks.Task<LW_18_2_PSD.HTService.getHTByIDResponse> getHTByIDAsync(LW_18_2_PSD.HTService.getHTByIDRequest request);
        
        // CODEGEN: Generating message contract since element name insertHTResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertHT", ReplyAction="*")]
        LW_18_2_PSD.HTService.insertHTResponse insertHT(LW_18_2_PSD.HTService.insertHTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertHT", ReplyAction="*")]
        System.Threading.Tasks.Task<LW_18_2_PSD.HTService.insertHTResponse> insertHTAsync(LW_18_2_PSD.HTService.insertHTRequest request);
        
        // CODEGEN: Generating message contract since element name getLastHTResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLastHT", ReplyAction="*")]
        LW_18_2_PSD.HTService.getLastHTResponse getLastHT(LW_18_2_PSD.HTService.getLastHTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLastHT", ReplyAction="*")]
        System.Threading.Tasks.Task<LW_18_2_PSD.HTService.getLastHTResponse> getLastHTAsync(LW_18_2_PSD.HTService.getLastHTRequest request);
        
        // CODEGEN: Generating message contract since element name getALLHTLISTResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getALLHTLIST", ReplyAction="*")]
        LW_18_2_PSD.HTService.getALLHTLISTResponse getALLHTLIST(LW_18_2_PSD.HTService.getALLHTLISTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getALLHTLIST", ReplyAction="*")]
        System.Threading.Tasks.Task<LW_18_2_PSD.HTService.getALLHTLISTResponse> getALLHTLISTAsync(LW_18_2_PSD.HTService.getALLHTLISTRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllHTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllHT", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.HTService.getAllHTRequestBody Body;
        
        public getAllHTRequest() {
        }
        
        public getAllHTRequest(LW_18_2_PSD.HTService.getAllHTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllHTRequestBody {
        
        public getAllHTRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllHTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllHTResponse", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.HTService.getAllHTResponseBody Body;
        
        public getAllHTResponse() {
        }
        
        public getAllHTResponse(LW_18_2_PSD.HTService.getAllHTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllHTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getAllHTResult;
        
        public getAllHTResponseBody() {
        }
        
        public getAllHTResponseBody(string getAllHTResult) {
            this.getAllHTResult = getAllHTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHTByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHTByID", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.HTService.getHTByIDRequestBody Body;
        
        public getHTByIDRequest() {
        }
        
        public getHTByIDRequest(LW_18_2_PSD.HTService.getHTByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getHTByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userID;
        
        public getHTByIDRequestBody() {
        }
        
        public getHTByIDRequestBody(int userID) {
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHTByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHTByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.HTService.getHTByIDResponseBody Body;
        
        public getHTByIDResponse() {
        }
        
        public getHTByIDResponse(LW_18_2_PSD.HTService.getHTByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getHTByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getHTByIDResult;
        
        public getHTByIDResponseBody() {
        }
        
        public getHTByIDResponseBody(string getHTByIDResult) {
            this.getHTByIDResult = getHTByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertHTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertHT", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.HTService.insertHTRequestBody Body;
        
        public insertHTRequest() {
        }
        
        public insertHTRequest(LW_18_2_PSD.HTService.insertHTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertHTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int headerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int userID;
        
        public insertHTRequestBody() {
        }
        
        public insertHTRequestBody(int headerID, int userID) {
            this.headerID = headerID;
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertHTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertHTResponse", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.HTService.insertHTResponseBody Body;
        
        public insertHTResponse() {
        }
        
        public insertHTResponse(LW_18_2_PSD.HTService.insertHTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertHTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertHTResult;
        
        public insertHTResponseBody() {
        }
        
        public insertHTResponseBody(string insertHTResult) {
            this.insertHTResult = insertHTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLastHTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLastHT", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.HTService.getLastHTRequestBody Body;
        
        public getLastHTRequest() {
        }
        
        public getLastHTRequest(LW_18_2_PSD.HTService.getLastHTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getLastHTRequestBody {
        
        public getLastHTRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLastHTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLastHTResponse", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.HTService.getLastHTResponseBody Body;
        
        public getLastHTResponse() {
        }
        
        public getLastHTResponse(LW_18_2_PSD.HTService.getLastHTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getLastHTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getLastHTResult;
        
        public getLastHTResponseBody() {
        }
        
        public getLastHTResponseBody(string getLastHTResult) {
            this.getLastHTResult = getLastHTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getALLHTLISTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getALLHTLIST", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.HTService.getALLHTLISTRequestBody Body;
        
        public getALLHTLISTRequest() {
        }
        
        public getALLHTLISTRequest(LW_18_2_PSD.HTService.getALLHTLISTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getALLHTLISTRequestBody {
        
        public getALLHTLISTRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getALLHTLISTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getALLHTLISTResponse", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.HTService.getALLHTLISTResponseBody Body;
        
        public getALLHTLISTResponse() {
        }
        
        public getALLHTLISTResponse(LW_18_2_PSD.HTService.getALLHTLISTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getALLHTLISTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getALLHTLISTResult;
        
        public getALLHTLISTResponseBody() {
        }
        
        public getALLHTLISTResponseBody(string getALLHTLISTResult) {
            this.getALLHTLISTResult = getALLHTLISTResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HTControllerSoapChannel : LW_18_2_PSD.HTService.HTControllerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HTControllerSoapClient : System.ServiceModel.ClientBase<LW_18_2_PSD.HTService.HTControllerSoap>, LW_18_2_PSD.HTService.HTControllerSoap {
        
        public HTControllerSoapClient() {
        }
        
        public HTControllerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HTControllerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HTControllerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HTControllerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LW_18_2_PSD.HTService.getAllHTResponse LW_18_2_PSD.HTService.HTControllerSoap.getAllHT(LW_18_2_PSD.HTService.getAllHTRequest request) {
            return base.Channel.getAllHT(request);
        }
        
        public string getAllHT() {
            LW_18_2_PSD.HTService.getAllHTRequest inValue = new LW_18_2_PSD.HTService.getAllHTRequest();
            inValue.Body = new LW_18_2_PSD.HTService.getAllHTRequestBody();
            LW_18_2_PSD.HTService.getAllHTResponse retVal = ((LW_18_2_PSD.HTService.HTControllerSoap)(this)).getAllHT(inValue);
            return retVal.Body.getAllHTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LW_18_2_PSD.HTService.getAllHTResponse> LW_18_2_PSD.HTService.HTControllerSoap.getAllHTAsync(LW_18_2_PSD.HTService.getAllHTRequest request) {
            return base.Channel.getAllHTAsync(request);
        }
        
        public System.Threading.Tasks.Task<LW_18_2_PSD.HTService.getAllHTResponse> getAllHTAsync() {
            LW_18_2_PSD.HTService.getAllHTRequest inValue = new LW_18_2_PSD.HTService.getAllHTRequest();
            inValue.Body = new LW_18_2_PSD.HTService.getAllHTRequestBody();
            return ((LW_18_2_PSD.HTService.HTControllerSoap)(this)).getAllHTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LW_18_2_PSD.HTService.getHTByIDResponse LW_18_2_PSD.HTService.HTControllerSoap.getHTByID(LW_18_2_PSD.HTService.getHTByIDRequest request) {
            return base.Channel.getHTByID(request);
        }
        
        public string getHTByID(int userID) {
            LW_18_2_PSD.HTService.getHTByIDRequest inValue = new LW_18_2_PSD.HTService.getHTByIDRequest();
            inValue.Body = new LW_18_2_PSD.HTService.getHTByIDRequestBody();
            inValue.Body.userID = userID;
            LW_18_2_PSD.HTService.getHTByIDResponse retVal = ((LW_18_2_PSD.HTService.HTControllerSoap)(this)).getHTByID(inValue);
            return retVal.Body.getHTByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LW_18_2_PSD.HTService.getHTByIDResponse> LW_18_2_PSD.HTService.HTControllerSoap.getHTByIDAsync(LW_18_2_PSD.HTService.getHTByIDRequest request) {
            return base.Channel.getHTByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<LW_18_2_PSD.HTService.getHTByIDResponse> getHTByIDAsync(int userID) {
            LW_18_2_PSD.HTService.getHTByIDRequest inValue = new LW_18_2_PSD.HTService.getHTByIDRequest();
            inValue.Body = new LW_18_2_PSD.HTService.getHTByIDRequestBody();
            inValue.Body.userID = userID;
            return ((LW_18_2_PSD.HTService.HTControllerSoap)(this)).getHTByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LW_18_2_PSD.HTService.insertHTResponse LW_18_2_PSD.HTService.HTControllerSoap.insertHT(LW_18_2_PSD.HTService.insertHTRequest request) {
            return base.Channel.insertHT(request);
        }
        
        public string insertHT(int headerID, int userID) {
            LW_18_2_PSD.HTService.insertHTRequest inValue = new LW_18_2_PSD.HTService.insertHTRequest();
            inValue.Body = new LW_18_2_PSD.HTService.insertHTRequestBody();
            inValue.Body.headerID = headerID;
            inValue.Body.userID = userID;
            LW_18_2_PSD.HTService.insertHTResponse retVal = ((LW_18_2_PSD.HTService.HTControllerSoap)(this)).insertHT(inValue);
            return retVal.Body.insertHTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LW_18_2_PSD.HTService.insertHTResponse> LW_18_2_PSD.HTService.HTControllerSoap.insertHTAsync(LW_18_2_PSD.HTService.insertHTRequest request) {
            return base.Channel.insertHTAsync(request);
        }
        
        public System.Threading.Tasks.Task<LW_18_2_PSD.HTService.insertHTResponse> insertHTAsync(int headerID, int userID) {
            LW_18_2_PSD.HTService.insertHTRequest inValue = new LW_18_2_PSD.HTService.insertHTRequest();
            inValue.Body = new LW_18_2_PSD.HTService.insertHTRequestBody();
            inValue.Body.headerID = headerID;
            inValue.Body.userID = userID;
            return ((LW_18_2_PSD.HTService.HTControllerSoap)(this)).insertHTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LW_18_2_PSD.HTService.getLastHTResponse LW_18_2_PSD.HTService.HTControllerSoap.getLastHT(LW_18_2_PSD.HTService.getLastHTRequest request) {
            return base.Channel.getLastHT(request);
        }
        
        public string getLastHT() {
            LW_18_2_PSD.HTService.getLastHTRequest inValue = new LW_18_2_PSD.HTService.getLastHTRequest();
            inValue.Body = new LW_18_2_PSD.HTService.getLastHTRequestBody();
            LW_18_2_PSD.HTService.getLastHTResponse retVal = ((LW_18_2_PSD.HTService.HTControllerSoap)(this)).getLastHT(inValue);
            return retVal.Body.getLastHTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LW_18_2_PSD.HTService.getLastHTResponse> LW_18_2_PSD.HTService.HTControllerSoap.getLastHTAsync(LW_18_2_PSD.HTService.getLastHTRequest request) {
            return base.Channel.getLastHTAsync(request);
        }
        
        public System.Threading.Tasks.Task<LW_18_2_PSD.HTService.getLastHTResponse> getLastHTAsync() {
            LW_18_2_PSD.HTService.getLastHTRequest inValue = new LW_18_2_PSD.HTService.getLastHTRequest();
            inValue.Body = new LW_18_2_PSD.HTService.getLastHTRequestBody();
            return ((LW_18_2_PSD.HTService.HTControllerSoap)(this)).getLastHTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LW_18_2_PSD.HTService.getALLHTLISTResponse LW_18_2_PSD.HTService.HTControllerSoap.getALLHTLIST(LW_18_2_PSD.HTService.getALLHTLISTRequest request) {
            return base.Channel.getALLHTLIST(request);
        }
        
        public string getALLHTLIST() {
            LW_18_2_PSD.HTService.getALLHTLISTRequest inValue = new LW_18_2_PSD.HTService.getALLHTLISTRequest();
            inValue.Body = new LW_18_2_PSD.HTService.getALLHTLISTRequestBody();
            LW_18_2_PSD.HTService.getALLHTLISTResponse retVal = ((LW_18_2_PSD.HTService.HTControllerSoap)(this)).getALLHTLIST(inValue);
            return retVal.Body.getALLHTLISTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LW_18_2_PSD.HTService.getALLHTLISTResponse> LW_18_2_PSD.HTService.HTControllerSoap.getALLHTLISTAsync(LW_18_2_PSD.HTService.getALLHTLISTRequest request) {
            return base.Channel.getALLHTLISTAsync(request);
        }
        
        public System.Threading.Tasks.Task<LW_18_2_PSD.HTService.getALLHTLISTResponse> getALLHTLISTAsync() {
            LW_18_2_PSD.HTService.getALLHTLISTRequest inValue = new LW_18_2_PSD.HTService.getALLHTLISTRequest();
            inValue.Body = new LW_18_2_PSD.HTService.getALLHTLISTRequestBody();
            return ((LW_18_2_PSD.HTService.HTControllerSoap)(this)).getALLHTLISTAsync(inValue);
        }
    }
}
