//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW_18_2_PSD.DTService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DTService.DTControllerSoap")]
    public interface DTControllerSoap {
        
        // CODEGEN: Generating message contract since element name getAllDTResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllDT", ReplyAction="*")]
        LW_18_2_PSD.DTService.getAllDTResponse getAllDT(LW_18_2_PSD.DTService.getAllDTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllDT", ReplyAction="*")]
        System.Threading.Tasks.Task<LW_18_2_PSD.DTService.getAllDTResponse> getAllDTAsync(LW_18_2_PSD.DTService.getAllDTRequest request);
        
        // CODEGEN: Generating message contract since element name getUserDTResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserDT", ReplyAction="*")]
        LW_18_2_PSD.DTService.getUserDTResponse getUserDT(LW_18_2_PSD.DTService.getUserDTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserDT", ReplyAction="*")]
        System.Threading.Tasks.Task<LW_18_2_PSD.DTService.getUserDTResponse> getUserDTAsync(LW_18_2_PSD.DTService.getUserDTRequest request);
        
        // CODEGEN: Generating message contract since element name insertDTResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertDT", ReplyAction="*")]
        LW_18_2_PSD.DTService.insertDTResponse insertDT(LW_18_2_PSD.DTService.insertDTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertDT", ReplyAction="*")]
        System.Threading.Tasks.Task<LW_18_2_PSD.DTService.insertDTResponse> insertDTAsync(LW_18_2_PSD.DTService.insertDTRequest request);
        
        // CODEGEN: Generating message contract since element name GetDTBYHEADERIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDTBYHEADERID", ReplyAction="*")]
        LW_18_2_PSD.DTService.GetDTBYHEADERIDResponse GetDTBYHEADERID(LW_18_2_PSD.DTService.GetDTBYHEADERIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDTBYHEADERID", ReplyAction="*")]
        System.Threading.Tasks.Task<LW_18_2_PSD.DTService.GetDTBYHEADERIDResponse> GetDTBYHEADERIDAsync(LW_18_2_PSD.DTService.GetDTBYHEADERIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllDTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllDT", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.DTService.getAllDTRequestBody Body;
        
        public getAllDTRequest() {
        }
        
        public getAllDTRequest(LW_18_2_PSD.DTService.getAllDTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllDTRequestBody {
        
        public getAllDTRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllDTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllDTResponse", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.DTService.getAllDTResponseBody Body;
        
        public getAllDTResponse() {
        }
        
        public getAllDTResponse(LW_18_2_PSD.DTService.getAllDTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllDTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getAllDTResult;
        
        public getAllDTResponseBody() {
        }
        
        public getAllDTResponseBody(string getAllDTResult) {
            this.getAllDTResult = getAllDTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserDTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserDT", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.DTService.getUserDTRequestBody Body;
        
        public getUserDTRequest() {
        }
        
        public getUserDTRequest(LW_18_2_PSD.DTService.getUserDTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserDTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int headerID;
        
        public getUserDTRequestBody() {
        }
        
        public getUserDTRequestBody(int headerID) {
            this.headerID = headerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserDTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserDTResponse", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.DTService.getUserDTResponseBody Body;
        
        public getUserDTResponse() {
        }
        
        public getUserDTResponse(LW_18_2_PSD.DTService.getUserDTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserDTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getUserDTResult;
        
        public getUserDTResponseBody() {
        }
        
        public getUserDTResponseBody(string getUserDTResult) {
            this.getUserDTResult = getUserDTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertDTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertDT", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.DTService.insertDTRequestBody Body;
        
        public insertDTRequest() {
        }
        
        public insertDTRequest(LW_18_2_PSD.DTService.insertDTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertDTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int headerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int qty;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int shoeID;
        
        public insertDTRequestBody() {
        }
        
        public insertDTRequestBody(int headerID, int qty, int shoeID) {
            this.headerID = headerID;
            this.qty = qty;
            this.shoeID = shoeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertDTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertDTResponse", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.DTService.insertDTResponseBody Body;
        
        public insertDTResponse() {
        }
        
        public insertDTResponse(LW_18_2_PSD.DTService.insertDTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertDTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertDTResult;
        
        public insertDTResponseBody() {
        }
        
        public insertDTResponseBody(string insertDTResult) {
            this.insertDTResult = insertDTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDTBYHEADERIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDTBYHEADERID", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.DTService.GetDTBYHEADERIDRequestBody Body;
        
        public GetDTBYHEADERIDRequest() {
        }
        
        public GetDTBYHEADERIDRequest(LW_18_2_PSD.DTService.GetDTBYHEADERIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDTBYHEADERIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int headerID;
        
        public GetDTBYHEADERIDRequestBody() {
        }
        
        public GetDTBYHEADERIDRequestBody(int headerID) {
            this.headerID = headerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDTBYHEADERIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDTBYHEADERIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.DTService.GetDTBYHEADERIDResponseBody Body;
        
        public GetDTBYHEADERIDResponse() {
        }
        
        public GetDTBYHEADERIDResponse(LW_18_2_PSD.DTService.GetDTBYHEADERIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDTBYHEADERIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDTBYHEADERIDResult;
        
        public GetDTBYHEADERIDResponseBody() {
        }
        
        public GetDTBYHEADERIDResponseBody(string GetDTBYHEADERIDResult) {
            this.GetDTBYHEADERIDResult = GetDTBYHEADERIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DTControllerSoapChannel : LW_18_2_PSD.DTService.DTControllerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DTControllerSoapClient : System.ServiceModel.ClientBase<LW_18_2_PSD.DTService.DTControllerSoap>, LW_18_2_PSD.DTService.DTControllerSoap {
        
        public DTControllerSoapClient() {
        }
        
        public DTControllerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DTControllerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DTControllerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DTControllerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LW_18_2_PSD.DTService.getAllDTResponse LW_18_2_PSD.DTService.DTControllerSoap.getAllDT(LW_18_2_PSD.DTService.getAllDTRequest request) {
            return base.Channel.getAllDT(request);
        }
        
        public string getAllDT() {
            LW_18_2_PSD.DTService.getAllDTRequest inValue = new LW_18_2_PSD.DTService.getAllDTRequest();
            inValue.Body = new LW_18_2_PSD.DTService.getAllDTRequestBody();
            LW_18_2_PSD.DTService.getAllDTResponse retVal = ((LW_18_2_PSD.DTService.DTControllerSoap)(this)).getAllDT(inValue);
            return retVal.Body.getAllDTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LW_18_2_PSD.DTService.getAllDTResponse> LW_18_2_PSD.DTService.DTControllerSoap.getAllDTAsync(LW_18_2_PSD.DTService.getAllDTRequest request) {
            return base.Channel.getAllDTAsync(request);
        }
        
        public System.Threading.Tasks.Task<LW_18_2_PSD.DTService.getAllDTResponse> getAllDTAsync() {
            LW_18_2_PSD.DTService.getAllDTRequest inValue = new LW_18_2_PSD.DTService.getAllDTRequest();
            inValue.Body = new LW_18_2_PSD.DTService.getAllDTRequestBody();
            return ((LW_18_2_PSD.DTService.DTControllerSoap)(this)).getAllDTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LW_18_2_PSD.DTService.getUserDTResponse LW_18_2_PSD.DTService.DTControllerSoap.getUserDT(LW_18_2_PSD.DTService.getUserDTRequest request) {
            return base.Channel.getUserDT(request);
        }
        
        public string getUserDT(int headerID) {
            LW_18_2_PSD.DTService.getUserDTRequest inValue = new LW_18_2_PSD.DTService.getUserDTRequest();
            inValue.Body = new LW_18_2_PSD.DTService.getUserDTRequestBody();
            inValue.Body.headerID = headerID;
            LW_18_2_PSD.DTService.getUserDTResponse retVal = ((LW_18_2_PSD.DTService.DTControllerSoap)(this)).getUserDT(inValue);
            return retVal.Body.getUserDTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LW_18_2_PSD.DTService.getUserDTResponse> LW_18_2_PSD.DTService.DTControllerSoap.getUserDTAsync(LW_18_2_PSD.DTService.getUserDTRequest request) {
            return base.Channel.getUserDTAsync(request);
        }
        
        public System.Threading.Tasks.Task<LW_18_2_PSD.DTService.getUserDTResponse> getUserDTAsync(int headerID) {
            LW_18_2_PSD.DTService.getUserDTRequest inValue = new LW_18_2_PSD.DTService.getUserDTRequest();
            inValue.Body = new LW_18_2_PSD.DTService.getUserDTRequestBody();
            inValue.Body.headerID = headerID;
            return ((LW_18_2_PSD.DTService.DTControllerSoap)(this)).getUserDTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LW_18_2_PSD.DTService.insertDTResponse LW_18_2_PSD.DTService.DTControllerSoap.insertDT(LW_18_2_PSD.DTService.insertDTRequest request) {
            return base.Channel.insertDT(request);
        }
        
        public string insertDT(int headerID, int qty, int shoeID) {
            LW_18_2_PSD.DTService.insertDTRequest inValue = new LW_18_2_PSD.DTService.insertDTRequest();
            inValue.Body = new LW_18_2_PSD.DTService.insertDTRequestBody();
            inValue.Body.headerID = headerID;
            inValue.Body.qty = qty;
            inValue.Body.shoeID = shoeID;
            LW_18_2_PSD.DTService.insertDTResponse retVal = ((LW_18_2_PSD.DTService.DTControllerSoap)(this)).insertDT(inValue);
            return retVal.Body.insertDTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LW_18_2_PSD.DTService.insertDTResponse> LW_18_2_PSD.DTService.DTControllerSoap.insertDTAsync(LW_18_2_PSD.DTService.insertDTRequest request) {
            return base.Channel.insertDTAsync(request);
        }
        
        public System.Threading.Tasks.Task<LW_18_2_PSD.DTService.insertDTResponse> insertDTAsync(int headerID, int qty, int shoeID) {
            LW_18_2_PSD.DTService.insertDTRequest inValue = new LW_18_2_PSD.DTService.insertDTRequest();
            inValue.Body = new LW_18_2_PSD.DTService.insertDTRequestBody();
            inValue.Body.headerID = headerID;
            inValue.Body.qty = qty;
            inValue.Body.shoeID = shoeID;
            return ((LW_18_2_PSD.DTService.DTControllerSoap)(this)).insertDTAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LW_18_2_PSD.DTService.GetDTBYHEADERIDResponse LW_18_2_PSD.DTService.DTControllerSoap.GetDTBYHEADERID(LW_18_2_PSD.DTService.GetDTBYHEADERIDRequest request) {
            return base.Channel.GetDTBYHEADERID(request);
        }
        
        public string GetDTBYHEADERID(int headerID) {
            LW_18_2_PSD.DTService.GetDTBYHEADERIDRequest inValue = new LW_18_2_PSD.DTService.GetDTBYHEADERIDRequest();
            inValue.Body = new LW_18_2_PSD.DTService.GetDTBYHEADERIDRequestBody();
            inValue.Body.headerID = headerID;
            LW_18_2_PSD.DTService.GetDTBYHEADERIDResponse retVal = ((LW_18_2_PSD.DTService.DTControllerSoap)(this)).GetDTBYHEADERID(inValue);
            return retVal.Body.GetDTBYHEADERIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LW_18_2_PSD.DTService.GetDTBYHEADERIDResponse> LW_18_2_PSD.DTService.DTControllerSoap.GetDTBYHEADERIDAsync(LW_18_2_PSD.DTService.GetDTBYHEADERIDRequest request) {
            return base.Channel.GetDTBYHEADERIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<LW_18_2_PSD.DTService.GetDTBYHEADERIDResponse> GetDTBYHEADERIDAsync(int headerID) {
            LW_18_2_PSD.DTService.GetDTBYHEADERIDRequest inValue = new LW_18_2_PSD.DTService.GetDTBYHEADERIDRequest();
            inValue.Body = new LW_18_2_PSD.DTService.GetDTBYHEADERIDRequestBody();
            inValue.Body.headerID = headerID;
            return ((LW_18_2_PSD.DTService.DTControllerSoap)(this)).GetDTBYHEADERIDAsync(inValue);
        }
    }
}
