//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW_18_2_PSD.CartReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CartReference.CartControllerSoap")]
    public interface CartControllerSoap {
        
        // CODEGEN: Generating message contract since element name getUserCartResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserCart", ReplyAction="*")]
        LW_18_2_PSD.CartReference.getUserCartResponse getUserCart(LW_18_2_PSD.CartReference.getUserCartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserCart", ReplyAction="*")]
        System.Threading.Tasks.Task<LW_18_2_PSD.CartReference.getUserCartResponse> getUserCartAsync(LW_18_2_PSD.CartReference.getUserCartRequest request);
        
        // CODEGEN: Generating message contract since element name insertCartResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertCart", ReplyAction="*")]
        LW_18_2_PSD.CartReference.insertCartResponse insertCart(LW_18_2_PSD.CartReference.insertCartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertCart", ReplyAction="*")]
        System.Threading.Tasks.Task<LW_18_2_PSD.CartReference.insertCartResponse> insertCartAsync(LW_18_2_PSD.CartReference.insertCartRequest request);
        
        // CODEGEN: Generating message contract since element name updateCartResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateCart", ReplyAction="*")]
        LW_18_2_PSD.CartReference.updateCartResponse updateCart(LW_18_2_PSD.CartReference.updateCartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateCart", ReplyAction="*")]
        System.Threading.Tasks.Task<LW_18_2_PSD.CartReference.updateCartResponse> updateCartAsync(LW_18_2_PSD.CartReference.updateCartRequest request);
        
        // CODEGEN: Generating message contract since element name deleteCartResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteCart", ReplyAction="*")]
        LW_18_2_PSD.CartReference.deleteCartResponse deleteCart(LW_18_2_PSD.CartReference.deleteCartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteCart", ReplyAction="*")]
        System.Threading.Tasks.Task<LW_18_2_PSD.CartReference.deleteCartResponse> deleteCartAsync(LW_18_2_PSD.CartReference.deleteCartRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserCartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserCart", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.CartReference.getUserCartRequestBody Body;
        
        public getUserCartRequest() {
        }
        
        public getUserCartRequest(LW_18_2_PSD.CartReference.getUserCartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserCartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        public getUserCartRequestBody() {
        }
        
        public getUserCartRequestBody(int userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserCartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserCartResponse", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.CartReference.getUserCartResponseBody Body;
        
        public getUserCartResponse() {
        }
        
        public getUserCartResponse(LW_18_2_PSD.CartReference.getUserCartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserCartResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getUserCartResult;
        
        public getUserCartResponseBody() {
        }
        
        public getUserCartResponseBody(string getUserCartResult) {
            this.getUserCartResult = getUserCartResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertCartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertCart", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.CartReference.insertCartRequestBody Body;
        
        public insertCartRequest() {
        }
        
        public insertCartRequest(LW_18_2_PSD.CartReference.insertCartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertCartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int shoeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int qty;
        
        public insertCartRequestBody() {
        }
        
        public insertCartRequestBody(int shoeID, int UserID, int qty) {
            this.shoeID = shoeID;
            this.UserID = UserID;
            this.qty = qty;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertCartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertCartResponse", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.CartReference.insertCartResponseBody Body;
        
        public insertCartResponse() {
        }
        
        public insertCartResponse(LW_18_2_PSD.CartReference.insertCartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertCartResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertCartResult;
        
        public insertCartResponseBody() {
        }
        
        public insertCartResponseBody(string insertCartResult) {
            this.insertCartResult = insertCartResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateCartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateCart", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.CartReference.updateCartRequestBody Body;
        
        public updateCartRequest() {
        }
        
        public updateCartRequest(LW_18_2_PSD.CartReference.updateCartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateCartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int shoeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int qty;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int updateQty;
        
        public updateCartRequestBody() {
        }
        
        public updateCartRequestBody(int userID, int shoeID, int qty, int updateQty) {
            this.userID = userID;
            this.shoeID = shoeID;
            this.qty = qty;
            this.updateQty = updateQty;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateCartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateCartResponse", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.CartReference.updateCartResponseBody Body;
        
        public updateCartResponse() {
        }
        
        public updateCartResponse(LW_18_2_PSD.CartReference.updateCartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateCartResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string updateCartResult;
        
        public updateCartResponseBody() {
        }
        
        public updateCartResponseBody(string updateCartResult) {
            this.updateCartResult = updateCartResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteCartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteCart", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.CartReference.deleteCartRequestBody Body;
        
        public deleteCartRequest() {
        }
        
        public deleteCartRequest(LW_18_2_PSD.CartReference.deleteCartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteCartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userID;
        
        public deleteCartRequestBody() {
        }
        
        public deleteCartRequestBody(int userID) {
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteCartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteCartResponse", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.CartReference.deleteCartResponseBody Body;
        
        public deleteCartResponse() {
        }
        
        public deleteCartResponse(LW_18_2_PSD.CartReference.deleteCartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteCartResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deleteCartResult;
        
        public deleteCartResponseBody() {
        }
        
        public deleteCartResponseBody(string deleteCartResult) {
            this.deleteCartResult = deleteCartResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CartControllerSoapChannel : LW_18_2_PSD.CartReference.CartControllerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CartControllerSoapClient : System.ServiceModel.ClientBase<LW_18_2_PSD.CartReference.CartControllerSoap>, LW_18_2_PSD.CartReference.CartControllerSoap {
        
        public CartControllerSoapClient() {
        }
        
        public CartControllerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CartControllerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CartControllerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CartControllerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LW_18_2_PSD.CartReference.getUserCartResponse LW_18_2_PSD.CartReference.CartControllerSoap.getUserCart(LW_18_2_PSD.CartReference.getUserCartRequest request) {
            return base.Channel.getUserCart(request);
        }
        
        public string getUserCart(int userId) {
            LW_18_2_PSD.CartReference.getUserCartRequest inValue = new LW_18_2_PSD.CartReference.getUserCartRequest();
            inValue.Body = new LW_18_2_PSD.CartReference.getUserCartRequestBody();
            inValue.Body.userId = userId;
            LW_18_2_PSD.CartReference.getUserCartResponse retVal = ((LW_18_2_PSD.CartReference.CartControllerSoap)(this)).getUserCart(inValue);
            return retVal.Body.getUserCartResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LW_18_2_PSD.CartReference.getUserCartResponse> LW_18_2_PSD.CartReference.CartControllerSoap.getUserCartAsync(LW_18_2_PSD.CartReference.getUserCartRequest request) {
            return base.Channel.getUserCartAsync(request);
        }
        
        public System.Threading.Tasks.Task<LW_18_2_PSD.CartReference.getUserCartResponse> getUserCartAsync(int userId) {
            LW_18_2_PSD.CartReference.getUserCartRequest inValue = new LW_18_2_PSD.CartReference.getUserCartRequest();
            inValue.Body = new LW_18_2_PSD.CartReference.getUserCartRequestBody();
            inValue.Body.userId = userId;
            return ((LW_18_2_PSD.CartReference.CartControllerSoap)(this)).getUserCartAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LW_18_2_PSD.CartReference.insertCartResponse LW_18_2_PSD.CartReference.CartControllerSoap.insertCart(LW_18_2_PSD.CartReference.insertCartRequest request) {
            return base.Channel.insertCart(request);
        }
        
        public string insertCart(int shoeID, int UserID, int qty) {
            LW_18_2_PSD.CartReference.insertCartRequest inValue = new LW_18_2_PSD.CartReference.insertCartRequest();
            inValue.Body = new LW_18_2_PSD.CartReference.insertCartRequestBody();
            inValue.Body.shoeID = shoeID;
            inValue.Body.UserID = UserID;
            inValue.Body.qty = qty;
            LW_18_2_PSD.CartReference.insertCartResponse retVal = ((LW_18_2_PSD.CartReference.CartControllerSoap)(this)).insertCart(inValue);
            return retVal.Body.insertCartResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LW_18_2_PSD.CartReference.insertCartResponse> LW_18_2_PSD.CartReference.CartControllerSoap.insertCartAsync(LW_18_2_PSD.CartReference.insertCartRequest request) {
            return base.Channel.insertCartAsync(request);
        }
        
        public System.Threading.Tasks.Task<LW_18_2_PSD.CartReference.insertCartResponse> insertCartAsync(int shoeID, int UserID, int qty) {
            LW_18_2_PSD.CartReference.insertCartRequest inValue = new LW_18_2_PSD.CartReference.insertCartRequest();
            inValue.Body = new LW_18_2_PSD.CartReference.insertCartRequestBody();
            inValue.Body.shoeID = shoeID;
            inValue.Body.UserID = UserID;
            inValue.Body.qty = qty;
            return ((LW_18_2_PSD.CartReference.CartControllerSoap)(this)).insertCartAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LW_18_2_PSD.CartReference.updateCartResponse LW_18_2_PSD.CartReference.CartControllerSoap.updateCart(LW_18_2_PSD.CartReference.updateCartRequest request) {
            return base.Channel.updateCart(request);
        }
        
        public string updateCart(int userID, int shoeID, int qty, int updateQty) {
            LW_18_2_PSD.CartReference.updateCartRequest inValue = new LW_18_2_PSD.CartReference.updateCartRequest();
            inValue.Body = new LW_18_2_PSD.CartReference.updateCartRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.shoeID = shoeID;
            inValue.Body.qty = qty;
            inValue.Body.updateQty = updateQty;
            LW_18_2_PSD.CartReference.updateCartResponse retVal = ((LW_18_2_PSD.CartReference.CartControllerSoap)(this)).updateCart(inValue);
            return retVal.Body.updateCartResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LW_18_2_PSD.CartReference.updateCartResponse> LW_18_2_PSD.CartReference.CartControllerSoap.updateCartAsync(LW_18_2_PSD.CartReference.updateCartRequest request) {
            return base.Channel.updateCartAsync(request);
        }
        
        public System.Threading.Tasks.Task<LW_18_2_PSD.CartReference.updateCartResponse> updateCartAsync(int userID, int shoeID, int qty, int updateQty) {
            LW_18_2_PSD.CartReference.updateCartRequest inValue = new LW_18_2_PSD.CartReference.updateCartRequest();
            inValue.Body = new LW_18_2_PSD.CartReference.updateCartRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.shoeID = shoeID;
            inValue.Body.qty = qty;
            inValue.Body.updateQty = updateQty;
            return ((LW_18_2_PSD.CartReference.CartControllerSoap)(this)).updateCartAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LW_18_2_PSD.CartReference.deleteCartResponse LW_18_2_PSD.CartReference.CartControllerSoap.deleteCart(LW_18_2_PSD.CartReference.deleteCartRequest request) {
            return base.Channel.deleteCart(request);
        }
        
        public string deleteCart(int userID) {
            LW_18_2_PSD.CartReference.deleteCartRequest inValue = new LW_18_2_PSD.CartReference.deleteCartRequest();
            inValue.Body = new LW_18_2_PSD.CartReference.deleteCartRequestBody();
            inValue.Body.userID = userID;
            LW_18_2_PSD.CartReference.deleteCartResponse retVal = ((LW_18_2_PSD.CartReference.CartControllerSoap)(this)).deleteCart(inValue);
            return retVal.Body.deleteCartResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LW_18_2_PSD.CartReference.deleteCartResponse> LW_18_2_PSD.CartReference.CartControllerSoap.deleteCartAsync(LW_18_2_PSD.CartReference.deleteCartRequest request) {
            return base.Channel.deleteCartAsync(request);
        }
        
        public System.Threading.Tasks.Task<LW_18_2_PSD.CartReference.deleteCartResponse> deleteCartAsync(int userID) {
            LW_18_2_PSD.CartReference.deleteCartRequest inValue = new LW_18_2_PSD.CartReference.deleteCartRequest();
            inValue.Body = new LW_18_2_PSD.CartReference.deleteCartRequestBody();
            inValue.Body.userID = userID;
            return ((LW_18_2_PSD.CartReference.CartControllerSoap)(this)).deleteCartAsync(inValue);
        }
    }
}
