//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW_18_2_PSD.UserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.UserControllerSoap")]
    public interface UserControllerSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doLogin", ReplyAction="*")]
        LW_18_2_PSD.UserService.doLoginResponse doLogin(LW_18_2_PSD.UserService.doLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<LW_18_2_PSD.UserService.doLoginResponse> doLoginAsync(LW_18_2_PSD.UserService.doLoginRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doRegister", ReplyAction="*")]
        LW_18_2_PSD.UserService.doRegisterResponse doRegister(LW_18_2_PSD.UserService.doRegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doRegister", ReplyAction="*")]
        System.Threading.Tasks.Task<LW_18_2_PSD.UserService.doRegisterResponse> doRegisterAsync(LW_18_2_PSD.UserService.doRegisterRequest request);
        
        // CODEGEN: Generating message contract since element name getAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAll", ReplyAction="*")]
        LW_18_2_PSD.UserService.getAllResponse getAll(LW_18_2_PSD.UserService.getAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAll", ReplyAction="*")]
        System.Threading.Tasks.Task<LW_18_2_PSD.UserService.getAllResponse> getAllAsync(LW_18_2_PSD.UserService.getAllRequest request);
        
        // CODEGEN: Generating message contract since element name doOrderResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doOrder", ReplyAction="*")]
        LW_18_2_PSD.UserService.doOrderResponse doOrder(LW_18_2_PSD.UserService.doOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<LW_18_2_PSD.UserService.doOrderResponse> doOrderAsync(LW_18_2_PSD.UserService.doOrderRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserID", ReplyAction="*")]
        LW_18_2_PSD.UserService.getUserIDResponse getUserID(LW_18_2_PSD.UserService.getUserIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserID", ReplyAction="*")]
        System.Threading.Tasks.Task<LW_18_2_PSD.UserService.getUserIDResponse> getUserIDAsync(LW_18_2_PSD.UserService.getUserIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doLogin", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.UserService.doLoginRequestBody Body;
        
        public doLoginRequest() {
        }
        
        public doLoginRequest(LW_18_2_PSD.UserService.doLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public doLoginRequestBody() {
        }
        
        public doLoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.UserService.doLoginResponseBody Body;
        
        public doLoginResponse() {
        }
        
        public doLoginResponse(LW_18_2_PSD.UserService.doLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string doLoginResult;
        
        public doLoginResponseBody() {
        }
        
        public doLoginResponseBody(string doLoginResult) {
            this.doLoginResult = doLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doRegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doRegister", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.UserService.doRegisterRequestBody Body;
        
        public doRegisterRequest() {
        }
        
        public doRegisterRequest(LW_18_2_PSD.UserService.doRegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doRegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public doRegisterRequestBody() {
        }
        
        public doRegisterRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doRegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doRegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.UserService.doRegisterResponseBody Body;
        
        public doRegisterResponse() {
        }
        
        public doRegisterResponse(LW_18_2_PSD.UserService.doRegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doRegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string doRegisterResult;
        
        public doRegisterResponseBody() {
        }
        
        public doRegisterResponseBody(string doRegisterResult) {
            this.doRegisterResult = doRegisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAll", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.UserService.getAllRequestBody Body;
        
        public getAllRequest() {
        }
        
        public getAllRequest(LW_18_2_PSD.UserService.getAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllRequestBody {
        
        public getAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.UserService.getAllResponseBody Body;
        
        public getAllResponse() {
        }
        
        public getAllResponse(LW_18_2_PSD.UserService.getAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getAllResult;
        
        public getAllResponseBody() {
        }
        
        public getAllResponseBody(string getAllResult) {
            this.getAllResult = getAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doOrder", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.UserService.doOrderRequestBody Body;
        
        public doOrderRequest() {
        }
        
        public doOrderRequest(LW_18_2_PSD.UserService.doOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int shoeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int qty;
        
        public doOrderRequestBody() {
        }
        
        public doOrderRequestBody(int shoeID, int userID, int qty) {
            this.shoeID = shoeID;
            this.userID = userID;
            this.qty = qty;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.UserService.doOrderResponseBody Body;
        
        public doOrderResponse() {
        }
        
        public doOrderResponse(LW_18_2_PSD.UserService.doOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string doOrderResult;
        
        public doOrderResponseBody() {
        }
        
        public doOrderResponseBody(string doOrderResult) {
            this.doOrderResult = doOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserID", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.UserService.getUserIDRequestBody Body;
        
        public getUserIDRequest() {
        }
        
        public getUserIDRequest(LW_18_2_PSD.UserService.getUserIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public getUserIDRequestBody() {
        }
        
        public getUserIDRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public LW_18_2_PSD.UserService.getUserIDResponseBody Body;
        
        public getUserIDResponse() {
        }
        
        public getUserIDResponse(LW_18_2_PSD.UserService.getUserIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getUserIDResult;
        
        public getUserIDResponseBody() {
        }
        
        public getUserIDResponseBody(string getUserIDResult) {
            this.getUserIDResult = getUserIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserControllerSoapChannel : LW_18_2_PSD.UserService.UserControllerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserControllerSoapClient : System.ServiceModel.ClientBase<LW_18_2_PSD.UserService.UserControllerSoap>, LW_18_2_PSD.UserService.UserControllerSoap {
        
        public UserControllerSoapClient() {
        }
        
        public UserControllerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserControllerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserControllerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserControllerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LW_18_2_PSD.UserService.doLoginResponse LW_18_2_PSD.UserService.UserControllerSoap.doLogin(LW_18_2_PSD.UserService.doLoginRequest request) {
            return base.Channel.doLogin(request);
        }
        
        public string doLogin(string username, string password) {
            LW_18_2_PSD.UserService.doLoginRequest inValue = new LW_18_2_PSD.UserService.doLoginRequest();
            inValue.Body = new LW_18_2_PSD.UserService.doLoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            LW_18_2_PSD.UserService.doLoginResponse retVal = ((LW_18_2_PSD.UserService.UserControllerSoap)(this)).doLogin(inValue);
            return retVal.Body.doLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LW_18_2_PSD.UserService.doLoginResponse> LW_18_2_PSD.UserService.UserControllerSoap.doLoginAsync(LW_18_2_PSD.UserService.doLoginRequest request) {
            return base.Channel.doLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<LW_18_2_PSD.UserService.doLoginResponse> doLoginAsync(string username, string password) {
            LW_18_2_PSD.UserService.doLoginRequest inValue = new LW_18_2_PSD.UserService.doLoginRequest();
            inValue.Body = new LW_18_2_PSD.UserService.doLoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((LW_18_2_PSD.UserService.UserControllerSoap)(this)).doLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LW_18_2_PSD.UserService.doRegisterResponse LW_18_2_PSD.UserService.UserControllerSoap.doRegister(LW_18_2_PSD.UserService.doRegisterRequest request) {
            return base.Channel.doRegister(request);
        }
        
        public string doRegister(string username, string password) {
            LW_18_2_PSD.UserService.doRegisterRequest inValue = new LW_18_2_PSD.UserService.doRegisterRequest();
            inValue.Body = new LW_18_2_PSD.UserService.doRegisterRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            LW_18_2_PSD.UserService.doRegisterResponse retVal = ((LW_18_2_PSD.UserService.UserControllerSoap)(this)).doRegister(inValue);
            return retVal.Body.doRegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LW_18_2_PSD.UserService.doRegisterResponse> LW_18_2_PSD.UserService.UserControllerSoap.doRegisterAsync(LW_18_2_PSD.UserService.doRegisterRequest request) {
            return base.Channel.doRegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<LW_18_2_PSD.UserService.doRegisterResponse> doRegisterAsync(string username, string password) {
            LW_18_2_PSD.UserService.doRegisterRequest inValue = new LW_18_2_PSD.UserService.doRegisterRequest();
            inValue.Body = new LW_18_2_PSD.UserService.doRegisterRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((LW_18_2_PSD.UserService.UserControllerSoap)(this)).doRegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LW_18_2_PSD.UserService.getAllResponse LW_18_2_PSD.UserService.UserControllerSoap.getAll(LW_18_2_PSD.UserService.getAllRequest request) {
            return base.Channel.getAll(request);
        }
        
        public string getAll() {
            LW_18_2_PSD.UserService.getAllRequest inValue = new LW_18_2_PSD.UserService.getAllRequest();
            inValue.Body = new LW_18_2_PSD.UserService.getAllRequestBody();
            LW_18_2_PSD.UserService.getAllResponse retVal = ((LW_18_2_PSD.UserService.UserControllerSoap)(this)).getAll(inValue);
            return retVal.Body.getAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LW_18_2_PSD.UserService.getAllResponse> LW_18_2_PSD.UserService.UserControllerSoap.getAllAsync(LW_18_2_PSD.UserService.getAllRequest request) {
            return base.Channel.getAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<LW_18_2_PSD.UserService.getAllResponse> getAllAsync() {
            LW_18_2_PSD.UserService.getAllRequest inValue = new LW_18_2_PSD.UserService.getAllRequest();
            inValue.Body = new LW_18_2_PSD.UserService.getAllRequestBody();
            return ((LW_18_2_PSD.UserService.UserControllerSoap)(this)).getAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LW_18_2_PSD.UserService.doOrderResponse LW_18_2_PSD.UserService.UserControllerSoap.doOrder(LW_18_2_PSD.UserService.doOrderRequest request) {
            return base.Channel.doOrder(request);
        }
        
        public string doOrder(int shoeID, int userID, int qty) {
            LW_18_2_PSD.UserService.doOrderRequest inValue = new LW_18_2_PSD.UserService.doOrderRequest();
            inValue.Body = new LW_18_2_PSD.UserService.doOrderRequestBody();
            inValue.Body.shoeID = shoeID;
            inValue.Body.userID = userID;
            inValue.Body.qty = qty;
            LW_18_2_PSD.UserService.doOrderResponse retVal = ((LW_18_2_PSD.UserService.UserControllerSoap)(this)).doOrder(inValue);
            return retVal.Body.doOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LW_18_2_PSD.UserService.doOrderResponse> LW_18_2_PSD.UserService.UserControllerSoap.doOrderAsync(LW_18_2_PSD.UserService.doOrderRequest request) {
            return base.Channel.doOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<LW_18_2_PSD.UserService.doOrderResponse> doOrderAsync(int shoeID, int userID, int qty) {
            LW_18_2_PSD.UserService.doOrderRequest inValue = new LW_18_2_PSD.UserService.doOrderRequest();
            inValue.Body = new LW_18_2_PSD.UserService.doOrderRequestBody();
            inValue.Body.shoeID = shoeID;
            inValue.Body.userID = userID;
            inValue.Body.qty = qty;
            return ((LW_18_2_PSD.UserService.UserControllerSoap)(this)).doOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LW_18_2_PSD.UserService.getUserIDResponse LW_18_2_PSD.UserService.UserControllerSoap.getUserID(LW_18_2_PSD.UserService.getUserIDRequest request) {
            return base.Channel.getUserID(request);
        }
        
        public string getUserID(string username) {
            LW_18_2_PSD.UserService.getUserIDRequest inValue = new LW_18_2_PSD.UserService.getUserIDRequest();
            inValue.Body = new LW_18_2_PSD.UserService.getUserIDRequestBody();
            inValue.Body.username = username;
            LW_18_2_PSD.UserService.getUserIDResponse retVal = ((LW_18_2_PSD.UserService.UserControllerSoap)(this)).getUserID(inValue);
            return retVal.Body.getUserIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LW_18_2_PSD.UserService.getUserIDResponse> LW_18_2_PSD.UserService.UserControllerSoap.getUserIDAsync(LW_18_2_PSD.UserService.getUserIDRequest request) {
            return base.Channel.getUserIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<LW_18_2_PSD.UserService.getUserIDResponse> getUserIDAsync(string username) {
            LW_18_2_PSD.UserService.getUserIDRequest inValue = new LW_18_2_PSD.UserService.getUserIDRequest();
            inValue.Body = new LW_18_2_PSD.UserService.getUserIDRequestBody();
            inValue.Body.username = username;
            return ((LW_18_2_PSD.UserService.UserControllerSoap)(this)).getUserIDAsync(inValue);
        }
    }
}
